language: objective-c
compiler: clang
script: make && make test
before_install:
- git clone https://github.com/macmade/xcode-coveralls.git /tmp/xcode-coveralls
- sudo xctool --project /tmp/xcode-coveralls/xcode-coveralls.xcodeproj --scheme xcode-coveralls DSTROOT=/ install
after_success:
- bash Scripts/coveralls.sh
