#-------------------------------------------------------------------------------
# Copyright (c) 2015, Jean-David Gadina - www.xs-labs.com
# Distributed under the Boost Software License, Version 1.0.
# 
# Boost Software License - Version 1.0 - August 17th, 2003
# 
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
# 
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# makelib configuration
#-------------------------------------------------------------------------------

include Submodules/makelib/Common.mk

PRODUCT             := XS-C++
PRODUCT_LIB         := libXS-C++
PRODUCT_DYLIB       := libXS-C++
PRODUCT_FRAMEWORK   := XS-C++
PREFIX_DYLIB        := /usr/local/lib/
PREFIX_FRAMEWORK    := /Library/Frameworks/
DIR_INC             := XS-C++/include/
DIR_SRC             := XS-C++/source/
DIR_RES             := XS-C++/
DIR_TESTS           := Unit-Tests/
EXT_C               := .cpp
EXT_H               := .h
CC                  := clang
LIBS                := -lpthread -lc++
FLAGS_OPTIM         := Os
FLAGS_WARN          := -Werror -Wall
FLAGS_STD           := c++11
FLAGS_OTHER         := -stdlib=libc++ -fno-strict-aliasing
XCODE_PROJECT       := IDE/Xcode/XS-C++.xcodeproj
XCODE_TEST_SCHEME   := XS-C++ Mac Static Library

FILES_C             := $(call GET_C_FILES, $(DIR_SRC))             \
                       $(call GET_C_FILES, $(DIR_SRC)Atomic/)      \
                       $(call GET_C_FILES, $(DIR_SRC)Threading/)

FILES_C_EXCLUDE     := %/Threading/NativeMutex-WIN32.cpp           \
                       %/Threading/NativeMutex-POSIX.cpp           \
                       %/Threading/Semaphore-APPLE.cpp             \
                       %/Threading/Semaphore-POSIX.cpp             \
                       %/Threading/Semaphore-WIN32.cpp

FILES               := $(filter-out $(FILES_C_EXCLUDE),$(FILES_C))
FILES_TESTS         := $(call GET_C_FILES, $(DIR_TESTS))

include Submodules/makelib/Targets.mk

#-------------------------------------------------------------------------------
# Custom targets
#-------------------------------------------------------------------------------

doc:
	
	@echo -e $(call PRINT,Documentation,universal,Generating the documentation)
	@doxygen Documentation/$(PRODUCT).doxygen
