#-------------------------------------------------------------------------------
# Copyright (c) 2015, Jean-David Gadina - www.xs-labs.com
# Distributed under the Boost Software License, Version 1.0.
# 
# Boost Software License - Version 1.0 - August 17th, 2003
# 
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
# 
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Products
#-------------------------------------------------------------------------------

# Procuct name
PRODUCT                 := XS-C++
PRODUCT_LIB             := lib$(PRODUCT)
PRODUCT_DYLIB           := lib$(PRODUCT)
PRODUCT_MAC_FRAMEWORK   := $(PRODUCT)
PRODUCT_IOS_LIB         := lib$(PRODUCT)-iOS

# Product paths
PREFIX_DYLIB            := /usr/local/lib/

#-------------------------------------------------------------------------------
# Paths
#-------------------------------------------------------------------------------

# Source directories
DIR_INC     := $(PRODUCT)/include/
DIR_SRC     := $(PRODUCT)/source/
DIR_RES     := $(PRODUCT)/
DIR_TESTS   := Unit-Tests/

#-------------------------------------------------------------------------------
# Includes
#-------------------------------------------------------------------------------

include Makefiles/Common.mk

ifeq ($(BUILD_TYPE),os-x)
    include Makefiles/OSX.mk
else
    include Makefiles/Linux.mk
endif

#-------------------------------------------------------------------------------
# Files
#-------------------------------------------------------------------------------

# All source files in the source directories
FILES_C         :=  $(call GET_C_FILES, $(DIR_SRC))             \
                    $(call GET_C_FILES, $(DIR_SRC)Atomic/)      \
                    $(call GET_C_FILES, $(DIR_SRC)Threading/)

# Platform specific files not to include in compilation
FILES_C_EXCLUDE :=  %/Threading/NativeMutex-WIN32.cpp \
                    %/Threading/NativeMutex-POSIX.cpp \
                    %/Threading/Semaphore-APPLE.cpp   \
                    %/Threading/Semaphore-POSIX.cpp   \
                    %/Threading/Semaphore-WIN32.cpp

# Files to compile
FILES           :=  $(filter-out $(FILES_C_EXCLUDE),$(FILES_C))

# Unit-test files
FILES_TESTS     :=  $(call GET_C_FILES, $(DIR_TESTS))

#-------------------------------------------------------------------------------
# Configuration
#-------------------------------------------------------------------------------

CC          := clang
LIBS        := -lpthread -lc++
FLAGS_OPTIM := Os
FLAGS_WARN  := -Werror -Wall
FLAGS_STD   := c++11
FLAGS_OTHER := -stdlib=libc++ -fno-strict-aliasing

#-------------------------------------------------------------------------------
# Custom targets
#-------------------------------------------------------------------------------

# Documentation
doc:
	
	@echo -e $(call PRINT,Documentation,universal,Generating the documentation)
	@doxygen Documentation/$(PRODUCT).doxygen

#-------------------------------------------------------------------------------
# Includes
#-------------------------------------------------------------------------------

include Makefiles/Targets.mk
